/**
 * Media library — the curated archive, placed.
 *
 * GENERATED by scripts/bulk-import (see the run log in the commit) from a visual
 * review of all 447 archive images and 214 short clips by an 11-agent curation
 * pass. Do not hand-edit: re-run the import.
 *
 * Standing exclusions applied during curation:
 *   - frames containing licensed or third-party character artwork
 *   - recruitment graphics (they carry a contact email address)
 *   - designed posters and text cards, as opposed to photographs
 *   - plates where third-party liner branding dominates the frame
 *   - anything blurred, very dark, or duplicated
 *
 * Captions describe only what is visible. No price, hour, or availability claim
 * is asserted from a photograph — those live in the sourced menu and location
 * records, which carry citations.
 *
 * 193 photographs · 14 silent clips
 */

export type GalleryShot = {
  image: string;
  imageAlt: string;
  caption?: string;
  /** Mosaic emphasis. Used sparingly — if everything is emphasised, nothing is. */
  span?: "feature" | "wide";
};

export type Clip = {
  src: string;
  poster: string;
  label: string;
  caption?: string;
};

/** The home strip: strongest frames, interleaved so neighbours differ. */
export const stripShots: GalleryShot[] = [
  { image: "/media/archive/cortado-latte-art.jpg", imageAlt: "A cortado in a small glass with a leaf-pattern latte art design on top.", caption: "cortado, latte art", span: "feature" },
  { image: "/media/archive/espresso-dark-pour.jpg", imageAlt: "A close, moody shot of espresso pouring from a portafilter into a white cup.", caption: "espresso, dark pour" },
  { image: "/media/archive/matcha-orange-cup.jpg", imageAlt: "A matcha latte with a light foam swirl served in an orange cup on a wooden ledge.", caption: "matcha, orange cup" },
  { image: "/media/archive/iced-drink-golden-light.jpg", imageAlt: "A hand holds up an iced drink in a red 5AM Club cup with green tea layered on top, backlit by a warm overhead light.", caption: "iced drink, golden light" },
  { image: "/media/archive/heart-latte-art.jpg", imageAlt: "A cappuccino with heart-shaped latte art and a dusting of red sprinkles, served in a white ribbed mug on a saucer.", caption: "heart latte art" },
  { image: "/media/archive/heart-in-the-cup.jpg", imageAlt: "A ceramic cup of coffee with heart-shaped latte art sits on a wooden table.", caption: "heart in the cup", span: "wide" },
  { image: "/media/archive/lavender-latte-in-hand.jpg", imageAlt: "A hand holds an iced lavender latte in a clear cup against a leafy green backdrop.", caption: "lavender latte, in hand" },
  { image: "/media/archive/three-drinks-one-board.jpg", imageAlt: "Three labeled iced drinks are arranged on a wooden paddle board against greenery.", caption: "three drinks, one board", span: "feature" },
  { image: "/media/archive/sunset-ombre-drink.jpg", imageAlt: "An ombre orange iced drink sits on a wooden tray outdoors surrounded by greenery.", caption: "sunset ombre drink" },
  { image: "/media/archive/sipping-on-sunshine-latte.jpg", imageAlt: "A yellow ceramic mug reading 'Sipping on sunshine' filled with latte art coffee, beside an oatmeal cookie on a wooden table.", caption: "sipping on sunshine latte" },
  { image: "/media/archive/smiley-and-sad-latte-art.jpg", imageAlt: "Two lattes side by side on a table, one with a smiley face and one with a frowning face drawn in the foam.", caption: "smiley and sad latte art" },
  { image: "/media/archive/coffee-and-a-good-book.jpg", imageAlt: "A latte with heart latte art, a croissant, and a copy of 'The 5 AM Club' book arranged on a wooden table in the cafe seating area.", caption: "coffee and a good book" },
  { image: "/media/archive/iced-coffee-greenery.jpg", imageAlt: "A glass of iced coffee with a branded logo sits on an outdoor table surrounded by green plants.", caption: "iced coffee, greenery" },
  { image: "/media/archive/drink-lineup-mirror-table.jpg", imageAlt: "Five different colored iced drinks are arranged closely on a mirrored table reflecting their glasses.", caption: "drink lineup, mirror table" },
  { image: "/media/archive/four-drinks-palm-leaf.jpg", imageAlt: "Four iced drinks in different colors are grouped closely together beside a large palm leaf.", caption: "four drinks, palm leaf", span: "feature" },
  { image: "/media/archive/espresso-mid-pour.jpg", imageAlt: "Espresso streaming from a portafilter into a white cup with visible steam against a dark background.", caption: "espresso, mid-pour" },
  { image: "/media/archive/cheers-string-lights-2.jpg", imageAlt: "Two hands hold up matching iced drinks in cups printed with the 5AM Club logo against a string-light backdrop.", caption: "cheers, string lights", span: "wide" },
  { image: "/media/archive/three-matcha-counter-line.jpg", imageAlt: "Three iced matcha drinks in cups printed with the 5AM Club logo sit on a counter with blurred customers behind.", caption: "three matcha, counter line" },
  { image: "/media/archive/the-double-pour.jpg", imageAlt: "Espresso streams from a portafilter into a measuring glass on an espresso machine.", caption: "the double pour" },
  { image: "/media/archive/matcha-and-morning-pumpkin.jpg", imageAlt: "An iced matcha drink and an orange 'Morning Pumpkin' mug sit together on a table by candlelight.", caption: "matcha and morning pumpkin" },
  { image: "/media/archive/matcha-and-latte-art-overhead.jpg", imageAlt: "An overhead view of an iced matcha and a latte with heart art on a wood table beside a small plant.", caption: "matcha and latte art, overhead" },
];

/** Per-page galleries. */
export const galleries: Record<string, GalleryShot[]> = {
  menu: [
  { image: "/media/archive/roasted-breakfast-potatoes.jpg", imageAlt: "A plate of roasted breakfast potatoes topped with sauce and grilled protein, with a drink and pastries blurred in the background.", caption: "roasted breakfast potatoes", span: "feature" },
  { image: "/media/archive/full-brunch-spread-outdoors.jpg", imageAlt: "A round outdoor table set with sliders, roasted potatoes, and other brunch dishes, with the 5AM Club logo overlaid and a street mural reflected in the window behind.", caption: "full brunch spread, outdoors" },
  { image: "/media/archive/tiramisu-rose-bud.jpg", imageAlt: "A square slice of tiramisu drizzled with chocolate sauce and garnished with a small pink rose bud on a white plate.", caption: "tiramisu, rose bud" },
  { image: "/media/archive/pumpkin-tart-hand.jpg", imageAlt: "A hand holds a pumpkin tart topped with pastry leaf decorations, with warm Christmas tree lights blurred in the background.", caption: "pumpkin tart, hand" },
  { image: "/media/archive/the-pastry-tray.jpg", imageAlt: "An overhead shot of assorted cream and fruit-topped pastries arranged on a wooden serving tray.", caption: "the pastry tray" },
  { image: "/media/archive/the-jerk-chicken-sandwich.jpg", imageAlt: "A jerk chicken sandwich on a brioche bun sits on a plate beside an iced drink.", caption: "the jerk chicken sandwich", span: "wide" },
  { image: "/media/archive/carrot-cake-cactus-corner.jpg", imageAlt: "A three-layer carrot cake slice with cream cheese frosting on a plate next to a small potted cactus.", caption: "carrot cake, cactus corner" },
  { image: "/media/archive/chocolate-sprinkles-donut.jpg", imageAlt: "A glazed donut covered in colorful sprinkles on a white plate, labeled 'Chocolate Sprinkles', more pastries blurred behind.", caption: "chocolate sprinkles donut", span: "feature" },
  { image: "/media/archive/grilled-cheese-cheese-pull.jpg", imageAlt: "A grilled panini sandwich cut in half showing melted cheese, plated on a wooden table with a leather couch behind.", caption: "grilled cheese, cheese pull" },
  { image: "/media/archive/honey-glaze-dripping.jpg", imageAlt: "A glazed donut with honey dripping down the side, with two other pastries and an iced drink blurred behind.", caption: "honey glaze, dripping" },
  { image: "/media/archive/sandwich-and-a-pink-drink.jpg", imageAlt: "A pulled chicken sandwich on ciabatta plated in front of a pink iced drink, with greenery in the background.", caption: "sandwich and a pink drink" },
  { image: "/media/archive/syrup-pour-waffles.jpg", imageAlt: "Syrup pours from a bottle onto a plate of waffles and fried chicken tenders on an outdoor table.", caption: "syrup pour, waffles" },
  { image: "/media/archive/club-sandwich-close-hold.jpg", imageAlt: "A hand holds a halved sandwich stacked with turkey, cheese, lettuce, and tomato in close-up.", caption: "club sandwich, close hold" },
  { image: "/media/archive/melted-cheese-gloved-hands.jpg", imageAlt: "Gloved hands hold a grilled sandwich with melted cheese pulling apart at the center.", caption: "melted cheese, gloved hands" },
  { image: "/media/archive/the-pastry-case.jpg", imageAlt: "A bakery display case holds croissants, cookies, a sandwich, and a muffin on wooden boards.", caption: "the pastry case", span: "feature" },
  { image: "/media/archive/tiramisu-rose-garnish.jpg", imageAlt: "A slice of tiramisu topped with a dried rose petal and cocoa dust sits on a white plate.", caption: "tiramisu, rose garnish" },
  { image: "/media/archive/grilled-sandwich-halved.jpg", imageAlt: "A gloved hand holds two halves of a grilled sandwich showing layers of tomato and greens.", caption: "grilled sandwich, halved", span: "wide" },
  { image: "/media/archive/cream-cheese-berry-rolls.jpg", imageAlt: "A tray of blueberry cream cheese sweet rolls topped with streusel crumble.", caption: "cream cheese berry rolls" },
  { image: "/media/archive/chocolate-rose-dome.jpg", imageAlt: "A round chocolate dessert dome topped with dried rose petals, served on a small gold plate.", caption: "chocolate rose dome" },
  { image: "/media/archive/croissant-iced-latte-chai.jpg", imageAlt: "A chicken salad croissant on a plate beside an iced latte in a 5AM Club cup and a mug of chai latte on a wooden table.", caption: "croissant, iced latte, chai" },
  { image: "/media/archive/matcha-pain-suisse.jpg", imageAlt: "A green matcha pain suisse pastry with white icing drizzle on a white plate, with a person gesturing in the blurred background.", caption: "matcha pain suisse" },
  { image: "/media/archive/chocolate-brownie-croissant.jpg", imageAlt: "A layered chocolate brownie coffee croissant topped with chocolate ganache, served on a white plate.", caption: "chocolate brownie croissant", span: "feature" },
  { image: "/media/archive/cinnamon-roll-pumpkin-tart.jpg", imageAlt: "A cinnamon roll on a small plate behind a pumpkin tart with a leaf-shaped pastry garnish, on a dark wood table.", caption: "cinnamon roll, pumpkin tart" },
  { image: "/media/archive/caramel-pecan-sticky-bun.jpg", imageAlt: "A close-up of a caramel pecan pastry on a wooden board with other pastries blurred behind it.", caption: "caramel pecan sticky bun" },
  { image: "/media/archive/s-mores-filled-donut.jpg", imageAlt: "A chocolate-dipped filled donut with a torched marshmallow topping on a white plate, labeled 'S'mores', other pastries blurred behind.", caption: "s'mores filled donut" },
  { image: "/media/archive/pulled-chicken-sandwich.jpg", imageAlt: "A pulled chicken sandwich with lettuce on ciabatta bread, plated with a bonsai tree blurred in the background.", caption: "pulled chicken sandwich" },
  { image: "/media/archive/egg-sandwich-gloved-hands.jpg", imageAlt: "Gloved hands hold a halved grilled sandwich filled with egg, cheese, and turkey bacon.", caption: "egg sandwich, gloved hands" },
  { image: "/media/archive/pancake-berry-compote-eggs.jpg", imageAlt: "A pancake topped with berry compote sits beside two fried eggs on a plate in warm light.", caption: "pancake, berry compote, eggs", span: "wide" },
  { image: "/media/archive/brownie-hand-held.jpg", imageAlt: "A hand holds a square brownie on a napkin with a barista in a branded apron blurred in the background.", caption: "brownie, hand held", span: "feature" },
  { image: "/media/archive/pastries-wooden-board.jpg", imageAlt: "A cupcake, a fruit tart, and a pastry displayed on a wooden board inside a glass bakery case.", caption: "pastries, wooden board" },
  { image: "/media/archive/the-sandwich.jpg", imageAlt: "A toasted sandwich with ham, egg, and greens sits open-faced on a plate lined with newsprint paper.", caption: "the sandwich" },
  { image: "/media/archive/tiramisu-tray.jpg", imageAlt: "A tray of tiramisu-style pastries topped with cocoa powder and chocolate wafers sits ready for service.", caption: "tiramisu tray" },
  { image: "/media/archive/affogato-evening-light.jpg", imageAlt: "A scoop of vanilla ice cream sitting in espresso, served in a glass, lit by warm evening light.", caption: "affogato, evening light" },
  { image: "/media/archive/iced-coffee-blue-sky.jpg", imageAlt: "A hand holds an iced coffee cup branded with the 5AM Club logo against a blue sky.", caption: "iced coffee, blue sky" },
  ],
  locations: [
  { image: "/media/archive/the-lounge-corner.jpg", imageAlt: "A leather couch with patterned pillows and a wooden coffee table in the cafe's seating area, pastel arches painted on the wall behind.", caption: "the lounge corner", span: "feature" },
  { image: "/media/archive/golden-hour-empty-tables.jpg", imageAlt: "Moody interior shot of empty cafe tables and chairs lit by golden sunset light streaming through the front windows.", caption: "golden hour, empty tables" },
  { image: "/media/archive/pendant-lights-dark-interior.jpg", imageAlt: "Three woven pendant lights hang above the branded logo on a dark interior wall.", caption: "pendant lights, dark interior" },
  { image: "/media/archive/evening-ambiance-workspace.jpg", imageAlt: "Customers seated at cafe tables working on laptops in warm evening lighting surrounded by hanging plants.", caption: "evening ambiance, workspace" },
  { image: "/media/archive/logo-wall-daylight.jpg", imageAlt: "The 5AM Club logo mounted on a wall beneath two woven pendant lamps.", caption: "logo wall, daylight" },
  { image: "/media/archive/the-loft-string-lights-on.jpg", imageAlt: "A long loft-style seating area strung with string lights, ceiling fans, and hanging plants.", caption: "the loft, string lights on", span: "wide" },
  { image: "/media/archive/the-lamp-lit-corner.jpg", imageAlt: "A cozy corner with hanging plants, a red lamp, and dark green armchairs lit warmly.", caption: "the lamp-lit corner" },
  { image: "/media/archive/sunset-through-the-loft.jpg", imageAlt: "Golden sunset light fills the café interior with the 5AM Club sign visible through the window and a customer's silhouette in the foreground.", caption: "sunset through the loft", span: "feature" },
  { image: "/media/archive/counter-and-menu-board.jpg", imageAlt: "Interior view of the cafe counter with an espresso machine, coffee grinder, and a chalkboard menu on the wall under pendant lights.", caption: "counter and menu board" },
  { image: "/media/archive/be-yourself-neon-wall.jpg", imageAlt: "A green living-wall backdrop with a neon sign reading 'Be Yourself everyone else is already Taken,' a person seated at a desk below.", caption: "be yourself, neon wall" },
  { image: "/media/archive/counter-black-and-white.jpg", imageAlt: "Black-and-white wide shot of the cafe counter and espresso machine with a staff member working at the register, 5AM Club branding on the wall.", caption: "counter, black and white" },
  { image: "/media/archive/storefront-window-signage.jpg", imageAlt: "A glass storefront window with the 5AM Club Coffee Shop logo and lettering etched on it.", caption: "storefront window, signage" },
  { image: "/media/archive/balcony-seating-plants.jpg", imageAlt: "An empty outdoor balcony seating area with small tables, wicker chairs, and potted plants overlooking the street.", caption: "balcony seating, plants" },
  { image: "/media/archive/vinyl-corner-by-the-window.jpg", imageAlt: "A vintage record player with colorful vinyl records sits near a window and a potted plant.", caption: "vinyl corner by the window" },
  { image: "/media/archive/logo-wall-after-dark.jpg", imageAlt: "The 5AM Club logo glows on a wall beneath three lit pendant lamps at night.", caption: "logo wall after dark", span: "feature" },
  { image: "/media/archive/be-yourself-corner-nook.jpg", imageAlt: "A neon sign reading 'Be Yourself' glows above a desk with a laptop and small plant.", caption: "be yourself, corner nook" },
  { image: "/media/archive/cart-logo-evening-crowd.jpg", imageAlt: "Two women pass by, silhouetted in front of the branded mobile cart lit at dusk.", caption: "cart logo, evening crowd", span: "wide" },
  { image: "/media/archive/the-sign-dusk.jpg", imageAlt: "The illuminated 5AM Club sign glows against a dusk sky with palm trees and a street below.", caption: "the sign, dusk" },
  { image: "/media/archive/storefront-sign-at-dusk.jpg", imageAlt: "The illuminated 5AM Club storefront sign glows against a sunset sky.", caption: "storefront sign at dusk" },
  { image: "/media/archive/cart-at-night.jpg", imageAlt: "The branded mobile coffee cart is set up at night with a staff member working behind it.", caption: "cart at night" },
  ],
  club: [
  { image: "/media/archive/silhouette-on-the-dance-floor.jpg", imageAlt: "A woman dances in silhouette, backlit against a doorway.", caption: "silhouette on the dance floor", span: "feature" },
  { image: "/media/archive/carnival-cups-raised.jpg", imageAlt: "Two women in carnival costumes hold 5AM Club cups near the brand's festival booth.", caption: "carnival, cups raised" },
  { image: "/media/archive/carnival-close-up-sip.jpg", imageAlt: "A woman in a pink carnival costume holds an iced drink close to the camera.", caption: "carnival close-up sip" },
  { image: "/media/archive/orange-costume-green-drink.jpg", imageAlt: "A woman in an orange carnival costume smiles while holding a green iced drink.", caption: "orange costume, green drink" },
  { image: "/media/archive/cheers-string-lights.jpg", imageAlt: "Two hands clink iced green drinks together under string lights at an event.", caption: "cheers, string lights" },
  { image: "/media/archive/sunset-drinks-in-hand.jpg", imageAlt: "Two men pose with iced drinks against a sunset sky at an outdoor event.", caption: "sunset, drinks in hand", span: "wide" },
  { image: "/media/archive/matcha-in-hand-sunset.jpg", imageAlt: "Two women smile at the camera each holding a branded iced matcha cup at an outdoor event.", caption: "matcha in hand, sunset" },
  { image: "/media/archive/giant-jenga-rooftop.jpg", imageAlt: "A man plays giant jenga on a rooftop terrace with a pink building in the background.", caption: "giant jenga, rooftop", span: "feature" },
  { image: "/media/archive/carnival-matcha-in-hand.jpg", imageAlt: "A woman in an orange carnival costume and red headwrap smiles while holding an iced green drink in a street crowd.", caption: "carnival, matcha in hand" },
  { image: "/media/archive/packed-house-upstairs-view.jpg", imageAlt: "A wide view from a loft mezzanine looking down on a packed crowd gathered around the counter during an evening event.", caption: "packed house, upstairs view" },
  { image: "/media/archive/flower-crown-live-vocals.jpg", imageAlt: "A man wearing a flower crown sings into a microphone surrounded by festive greenery decor.", caption: "flower crown, live vocals" },
  { image: "/media/archive/duet-flowers-and-neon.jpg", imageAlt: "A man and woman duet at microphones together, both adorned with flowers, in front of colorful neon signage.", caption: "duet, flowers and neon" },
  { image: "/media/archive/dj-at-the-decks.jpg", imageAlt: "A DJ wearing headphones and sunglasses performs at a turntable setup during an event.", caption: "dj at the decks" },
  { image: "/media/archive/cheers-at-the-event.jpg", imageAlt: "Two men holding iced 5AM Club drinks smile for a photo outdoors.", caption: "cheers at the event" },
  { image: "/media/archive/crowd-on-the-balcony.jpg", imageAlt: "A group of men gather on a decorated balcony holding drinks at an event.", caption: "crowd on the balcony", span: "feature" },
  { image: "/media/archive/sipping-under-the-tent.jpg", imageAlt: "A man in glasses drinks an iced beverage through a straw under a colorful event tent.", caption: "sipping under the tent" },
  { image: "/media/archive/night-market-arms-up.jpg", imageAlt: "A woman dances with both arms raised at a crowded night market, balancing a cup on her head.", caption: "night market, arms up", span: "wide" },
  { image: "/media/archive/matcha-cup-blue-top.jpg", imageAlt: "A woman in a blue halter top smiles while holding a branded iced matcha cup at an event.", caption: "matcha cup, blue top" },
  { image: "/media/archive/dominoes-cart-drink.jpg", imageAlt: "Two women play a table game together with a branded iced drink nearby.", caption: "dominoes, cart drink" },
  { image: "/media/archive/playing-cards-mural-wall.jpg", imageAlt: "Two people play a large-format card game in front of a colorful mural.", caption: "playing cards, mural wall" },
  { image: "/media/archive/jenga-tower-falling.jpg", imageAlt: "Two men reach toward a giant jenga tower as it topples on a rooftop terrace.", caption: "jenga tower, falling" },
  { image: "/media/archive/vocalist-vinyl-wall.jpg", imageAlt: "A woman sings into a microphone on stage in front of a wall covered in framed vinyl records, lit by string lights.", caption: "vocalist, vinyl wall", span: "feature" },
  { image: "/media/archive/spoken-word-night-session.jpg", imageAlt: "A performer with a bandana and dreadlocks speaks into a microphone while seated on stage during a night event.", caption: "spoken word, night session" },
  { image: "/media/archive/vocals-side-profile.jpg", imageAlt: "A woman sings into a microphone in profile, lit warmly against a dim interior.", caption: "vocals, side profile" },
  { image: "/media/archive/gift-bags-laughter.jpg", imageAlt: "A group of women laugh and exchange teal gift bags around a small wooden table.", caption: "gift bags, laughter" },
  { image: "/media/archive/striped-beanie-vocals.jpg", imageAlt: "A man wearing a yellow and black striped beanie sings into a microphone in front of a garland-draped window.", caption: "striped beanie, vocals" },
  { image: "/media/archive/call-and-response.jpg", imageAlt: "A man in a black beanie and rasta-colored jacket gestures while singing into a microphone on stage.", caption: "call and response" },
  { image: "/media/archive/the-whole-crew-together.jpg", imageAlt: "A large group poses together indoors in front of a wall of framed album art.", caption: "the whole crew together", span: "wide" },
  { image: "/media/archive/family-matching-pajamas.jpg", imageAlt: "A family of four in matching red pajamas smiles together in front of a decorated Christmas tree.", caption: "family, matching pajamas", span: "feature" },
  { image: "/media/archive/smiling-with-matcha.jpg", imageAlt: "A woman smiles while holding an iced green matcha drink under string lights.", caption: "smiling with matcha" },
  ],
  story: [
  { image: "/media/archive/iridescent-mug-big-smile.jpg", imageAlt: "A woman in an orange top smiles while holding an iridescent metal mug at an event.", caption: "iridescent mug, big smile", span: "feature" },
  { image: "/media/archive/two-friends-two-drinks.jpg", imageAlt: "Two women pose together at an event, each holding an iced drink.", caption: "two friends, two drinks" },
  { image: "/media/archive/back-to-back-the-loft.jpg", imageAlt: "Two staff members pose back to back smiling inside a loft-style interior with a spiral staircase.", caption: "back to back, the loft" },
  { image: "/media/archive/three-staff-cart-smiles.jpg", imageAlt: "Three staff members in brown branded shirts smile together behind a cart with sauce bottles.", caption: "three staff, cart smiles" },
  { image: "/media/archive/most-focused-team-cheer.jpg", imageAlt: "A staff member holds a 'Most Focused' award certificate while several coworkers in festive outfits gather around her smiling.", caption: "most focused, team cheer" },
  { image: "/media/archive/yellow-top-garden-light.jpg", imageAlt: "A woman in a yellow ruffled top and sunglasses smiles over her shoulder in a plant-filled outdoor seating area.", caption: "yellow top, garden light", span: "wide" },
  { image: "/media/archive/father-and-daughter.jpg", imageAlt: "A man and a young girl stand smiling together inside a plant-decorated seating area.", caption: "father and daughter" },
  { image: "/media/archive/journaling-in-the-sun.jpg", imageAlt: "A woman in a yellow ruffled top writes in a notebook at an outdoor café table surrounded by plants.", caption: "journaling in the sun", span: "feature" },
  { image: "/media/archive/laughing-in-golden-light.jpg", imageAlt: "A woman in a yellow ruffled top and sunglasses laughs while seated outdoors.", caption: "laughing in golden light" },
  { image: "/media/archive/evening-in-the-rattan-chair.jpg", imageAlt: "A woman smiles while seated in a woven rattan egg chair, holding her phone in the evening.", caption: "evening in the rattan chair" },
  { image: "/media/archive/cheers-outside-the-shop.jpg", imageAlt: "Two women raise iced drinks in a toast at an outdoor table beneath the 5AM Club sign.", caption: "cheers outside the shop" },
  { image: "/media/archive/couple-on-the-record-wall-couch.jpg", imageAlt: "A couple sits together on an orange couch beneath a wall of framed vinyl records.", caption: "couple on the record wall couch" },
  { image: "/media/archive/peace-sign-at-the-bar.jpg", imageAlt: "Two staff members smile behind the counter, one flashing a peace sign, in front of a green mural.", caption: "peace sign at the bar" },
  { image: "/media/archive/sip-beneath-the-greenery.jpg", imageAlt: "A man in a white t-shirt drinks from a cup in front of a plant-filled archway nook.", caption: "sip beneath the greenery" },
  { image: "/media/archive/barista-fresh-pour.jpg", imageAlt: "A smiling barista holds up a branded coffee cup in front of the espresso machine and shelves.", caption: "barista, fresh pour", span: "feature" },
  { image: "/media/archive/mother-daughter-christmas.jpg", imageAlt: "A mother and young daughter in matching Christmas-themed pajamas pose together indoors near a decorated tree.", caption: "mother, daughter, christmas" },
  { image: "/media/archive/mother-son-snowman-sweaters.jpg", imageAlt: "A mother and son wearing matching blue snowman-print sweaters with red sleeves pose together in front of a Christmas tree.", caption: "mother, son, snowman sweaters", span: "wide" },
  { image: "/media/archive/the-boy-who-started-it.jpg", imageAlt: "A faded childhood photo of a smiling boy, overlaid with text about him growing up to open the coffee shop.", caption: "the boy who started it" },
  { image: "/media/archive/counter-conversation.jpg", imageAlt: "A young man in a cap leans on the counter, smiling, with a street scene blurred behind him.", caption: "counter conversation" },
  { image: "/media/archive/the-staff-arm-in-arm.jpg", imageAlt: "Four staff members in maroon 5AM Club shirts pose together with arms around each other.", caption: "the staff, arm in arm" },
  { image: "/media/archive/shirt-reveal-storefront-view.jpg", imageAlt: "A staff member holds open her maroon 5AM Club shirt with the storefront sign visible through the window behind her.", caption: "shirt reveal, storefront view" },
  { image: "/media/archive/focused-behind-the-counter.jpg", imageAlt: "A staff member in a pink shirt works quietly behind the counter.", caption: "focused behind the counter", span: "feature" },
  { image: "/media/archive/sunglasses-and-iced-coffee.jpg", imageAlt: "A woman in sunglasses drinks iced coffee outside a colorful storefront wall.", caption: "sunglasses and iced coffee" },
  { image: "/media/archive/behind-the-espresso-machine.jpg", imageAlt: "A staff member in a pink uniform shirt operates the espresso machine at an event booth.", caption: "behind the espresso machine" },
  { image: "/media/archive/reindeer-ears-team-photo.jpg", imageAlt: "Three staff members in matching aprons pose together wearing red reindeer antler headbands.", caption: "reindeer ears, team photo" },
  { image: "/media/archive/waving-hello-market-shift.jpg", imageAlt: "A staff member with a flower in her hair waves while wearing a black glove at an event.", caption: "waving hello, market shift" },
  { image: "/media/archive/father-s-day-hug-upstairs.jpg", imageAlt: "A woman hugs a seated man from behind in a cafe interior with shelving and string lights.", caption: "father's day hug, upstairs" },
  { image: "/media/archive/best-barista-santa-hat.jpg", imageAlt: "A staff member in a Santa hat smiles while holding a 'Best Barista-R' award certificate.", caption: "best barista, santa hat", span: "wide" },
  ],
};

/** The full archive page, grouped by what the frame is of. */
export const archiveGroups: { id: string; title: string; shots: GalleryShot[] }[] = [
  { id: "drinks", title: "Drinks", shots: [
  { image: "/media/archive/matchagato-close-up.jpg", imageAlt: "A glass of matcha topped with a scoop of vanilla ice cream, set on a wooden table.", caption: "matchagato, close up", span: "feature" },
  { image: "/media/archive/latte-art-overhead.jpg", imageAlt: "Two coffee drinks viewed from above, one topped with a heart-shaped latte art pour.", caption: "latte art, overhead" },
  { image: "/media/archive/oreo-rodeo-drink.jpg", imageAlt: "An iced chocolate drink topped with whipped cream, crushed cookies, and chocolate drizzle in a clear cup.", caption: "oreo rodeo drink" },
  { image: "/media/archive/matcha-holiday-decor.jpg", imageAlt: "An iced matcha latte in a 5AM Club cup on a wooden table, with a heart-shaped wreath and holiday tinsel in the background.", caption: "matcha, holiday decor" },
  { image: "/media/archive/lavender-oat-matcha-layers.jpg", imageAlt: "A layered lavender oat matcha drink topped with cream sits on a counter.", caption: "lavender oat matcha layers" },
  { image: "/media/archive/strawberry-creamsicle-whipped.jpg", imageAlt: "A pink strawberry creamsicle drink topped with whipped cream sits on a scale on the counter.", caption: "strawberry creamsicle, whipped", span: "wide" },
  { image: "/media/archive/lavender-tea-golden-light.jpg", imageAlt: "A hand holds an iced lavender green tea lemonade outdoors against greenery.", caption: "lavender tea, golden light" },
  { image: "/media/archive/two-drinks-warm-counter.jpg", imageAlt: "Two iced 5AM Club drinks sit on a counter with warm under-lighting and a chalkboard sign behind them.", caption: "two drinks, warm counter", span: "feature" },
  { image: "/media/archive/matcha-and-berry-overhead.jpg", imageAlt: "An overhead shot of an iced matcha drink and a berry cream drink on a wooden board.", caption: "matcha and berry, overhead" },
  { image: "/media/archive/pink-ribbon-latte-art.jpg", imageAlt: "A latte with a pink ribbon design in the foam next to a pink iced drink on a wood table.", caption: "pink ribbon latte art" },
  { image: "/media/archive/matcha-textured-cup.jpg", imageAlt: "A bright green matcha latte in a white textured ceramic cup on a wooden counter.", caption: "matcha, textured cup" },
  { image: "/media/archive/iced-or-hot-your-call.jpg", imageAlt: "Two hands each holding a 5AM Club cup, one iced coffee and one hot cup, with 'Iced or Hot?' text overlay.", caption: "iced or hot, your call" },
  { image: "/media/archive/latte-mural-corner.jpg", imageAlt: "A latte with rosette art in a stoneware cup and saucer on a wooden table, with a pastel mural and leather couch in the background.", caption: "latte, mural corner" },
  { image: "/media/archive/independence-day-latte-art.jpg", imageAlt: "A latte with a Trinidad and Tobago flag drawn in the foam, captioned 'Happy Independence Day, Sweet T&T'.", caption: "independence day latte art" },
  { image: "/media/archive/iced-coffee-to-go-2.jpg", imageAlt: "A hand holds an iced coffee cup and a wrapped chocolate pastry on a napkin outdoors in sunlight.", caption: "iced coffee to go", span: "feature" },
  { image: "/media/archive/latte-art-5am-logo.jpg", imageAlt: "A cappuccino in a white ribbed mug with the 5AM Club logo drawn into the foam.", caption: "latte art, 5am logo" },
  { image: "/media/archive/iced-coffee-golden-hour.jpg", imageAlt: "An iced coffee in a cup printed with the 5AM Club logo sits on a counter lit by warm golden-hour light.", caption: "iced coffee, golden hour", span: "wide" },
  { image: "/media/archive/iced-coffee-hand-held.jpg", imageAlt: "A hand holds up an iced coffee in a cup printed with the 5AM Club logo with an orange pendant light behind.", caption: "iced coffee, hand-held" },
  { image: "/media/archive/to-go-in-the-car.jpg", imageAlt: "An iced coffee in a cup printed with the 5AM Club logo sits in a car's cupholder against black leather seats.", caption: "to-go, in the car" },
  { image: "/media/archive/iced-matcha-candlelight.jpg", imageAlt: "An iced matcha drink in a 5AM Club cup sits on a table with warm bokeh lights behind it.", caption: "iced matcha, candlelight" },
  { image: "/media/archive/two-matchas-for-you.jpg", imageAlt: "Two iced matcha lattes in white and yellow cups sit on a wooden table.", caption: "two matchas, for you" },
  { image: "/media/archive/independence-day-latte-art-2.jpg", imageAlt: "A cappuccino topped with Trinidad and Tobago flag-themed latte art sits on a saucer.", caption: "independence day latte art", span: "feature" },
  { image: "/media/archive/iced-trio-on-the-table.jpg", imageAlt: "Three iced coffee drinks in mason-style glass mugs sit together on a wooden table.", caption: "iced trio on the table" },
  ] },
  { id: "texture", title: "Texture", shots: [
  { image: "/media/archive/matcha-tool-flat-lay.jpg", imageAlt: "A wooden board laid out with matcha-making tools — a green bowl, bamboo whisk, sieve, and vanilla paste — beside a chalkboard labeled MATCHA.", caption: "matcha tool flat lay", span: "feature" },
  { image: "/media/archive/grinding-gloves-on.jpg", imageAlt: "A staff member in gloves and glasses operates coffee equipment closely.", caption: "grinding, gloves on" },
  { image: "/media/archive/pumpkin-split-open.jpg", imageAlt: "Close-up of a pumpkin cut in half showing its stringy orange interior in sunlight.", caption: "pumpkin, split open" },
  { image: "/media/archive/matcha-prep-overhead.jpg", imageAlt: "Overhead view of matcha preparation tools including a sifter, whisk, tin of matcha powder, and a finished bowl of matcha.", caption: "matcha prep, overhead" },
  { image: "/media/archive/coffee-beans-overhead.jpg", imageAlt: "Overhead shot of a cup of coffee with latte art on a dark plate scattered with coffee beans and a pair of wireless earbuds.", caption: "coffee, beans, overhead" },
  { image: "/media/archive/hands-passing-the-cup.jpg", imageAlt: "Two hands pass a branded iced drink cup between them in close-up.", caption: "hands, passing the cup", span: "wide" },
  { image: "/media/archive/iced-coffee-close-up.jpg", imageAlt: "Macro close-up of an iced coffee drink showing ice and swirled liquid.", caption: "iced coffee, close up" },
  { image: "/media/archive/grounds-portafilter.jpg", imageAlt: "A hand holds a portafilter filled with fresh ground coffee near the espresso machine.", caption: "grounds, portafilter", span: "feature" },
  { image: "/media/archive/coffee-beans-close-up.jpg", imageAlt: "A close overhead view of roasted coffee beans of varying shades.", caption: "coffee beans, close up" },
  { image: "/media/archive/5am-club-caps.jpg", imageAlt: "Two black 5AM Club branded caps rest on a wooden shelf near hanging clothes.", caption: "5am club caps" },
  { image: "/media/archive/the-mug-collection.jpg", imageAlt: "A wall of cubbies displays an eclectic collection of novelty mugs, including one branded 5AM.", caption: "the mug collection" },
  ] },
  { id: "cart", title: "Cart", shots: [
  { image: "/media/archive/hug-at-the-cart-menu-board.jpg", imageAlt: "Two women embrace at a branded pop-up cart with a drink menu and truck in the background.", caption: "hug at the cart, menu board", span: "feature" },
  ] },
  { id: "people", title: "People", shots: [
  { image: "/media/archive/most-calm-under-pressure.jpg", imageAlt: "A staff member smiles while holding a 'Most Calm Under Pressure' award certificate in the cafe.", caption: "most calm under pressure", span: "feature" },
  { image: "/media/archive/shining-star-staff-award.jpg", imageAlt: "A staff member in a pink patterned hat smiles holding a 'Shining Star' award certificate.", caption: "shining star, staff award" },
  { image: "/media/archive/all-rounder-playful.jpg", imageAlt: "A staff member in a Santa hat sticks out her tongue playfully while holding an 'All Rounder' award certificate.", caption: "all rounder, playful" },
  { image: "/media/archive/positivi-tea-award.jpg", imageAlt: "A staff member in a festive outfit blows a kiss while holding a 'Positivi-Tea Award' certificate.", caption: "positivi-tea award" },
  { image: "/media/archive/most-calm-under-pressure-2.jpg", imageAlt: "A smiling staff member with long locs holds a 'Most Calm Under Pressure' award certificate.", caption: "most calm under pressure" },
  { image: "/media/archive/friends-table-celebration.jpg", imageAlt: "A group of women in colorful outfits gathered around a small table, laughing and celebrating together in the cafe.", caption: "friends, table celebration", span: "wide" },
  { image: "/media/archive/baristas-prepping-drinks.jpg", imageAlt: "Two baristas in matching branded t-shirts prepare drinks together behind the counter.", caption: "baristas, prepping drinks" },
  { image: "/media/archive/cheers-two-drinks-up.jpg", imageAlt: "A smiling man in a cardigan holds up two iced drinks under hanging greenery inside the cafe.", caption: "cheers, two drinks up", span: "feature" },
  { image: "/media/archive/staff-portrait-gallery-wall.jpg", imageAlt: "A smiling staff member with long locs stands in front of framed artwork on the cafe wall.", caption: "staff portrait, gallery wall" },
  { image: "/media/archive/showing-off-the-shirt.jpg", imageAlt: "A staff member holds up her maroon 5AM Club logo t-shirt while standing in a doorway with the storefront sign visible outside.", caption: "showing off the shirt" },
  { image: "/media/archive/pink-shirt-register.jpg", imageAlt: "A smiling staff member in a pink uniform shirt and 5AM Club tie works at a point-of-sale station under string lights.", caption: "pink shirt, register" },
  { image: "/media/archive/terrace-afternoon-catch-up.jpg", imageAlt: "A woman and a man sit at an outdoor cafe table with an iced drink between them, a city street visible behind.", caption: "terrace, afternoon catch-up" },
  { image: "/media/archive/thumbs-up-staff-smiles.jpg", imageAlt: "Two staff members in dark overalls smile and give a thumbs up near a spiral staircase.", caption: "thumbs up, staff smiles" },
  { image: "/media/archive/floral-wall-friends.jpg", imageAlt: "Three young customers sit together on a bench in front of a floral wall backdrop.", caption: "floral wall, friends" },
  { image: "/media/archive/heart-hands-closing-shift.jpg", imageAlt: "Two staff members make heart and thumbs-up hand signs together near a display case.", caption: "heart hands, closing shift", span: "feature" },
  { image: "/media/archive/staff-member-tablet-in-hand.jpg", imageAlt: "A smiling staff member in a 5AM Club shirt holds a red tablet indoors.", caption: "staff member, tablet in hand" },
  { image: "/media/archive/three-friends-coffee-break.jpg", imageAlt: "Three women sit smiling around a small round table with coffee cups.", caption: "three friends, coffee break", span: "wide" },
  { image: "/media/archive/reading-on-the-rooftop.jpg", imageAlt: "A woman relaxes in a winged rattan chair on a rooftop terrace, tablet in hand.", caption: "reading on the rooftop" },
  { image: "/media/archive/selfie-by-the-mural.jpg", imageAlt: "A couple takes a selfie outdoors near a colorful mural and busy street.", caption: "selfie by the mural" },
  { image: "/media/archive/iced-coffee-city-view.jpg", imageAlt: "A couple sits at an outdoor café table with an iced coffee, city buildings in the background.", caption: "iced coffee, city view" },
  { image: "/media/archive/coffee-catching-up.jpg", imageAlt: "Two women sit at a table with coffee cups, smiling, beneath a curved orange booth backdrop.", caption: "coffee, catching up" },
  { image: "/media/archive/behind-the-espresso-machine-2.jpg", imageAlt: "A barista works at the espresso machine beneath the 5AM Club wall sign.", caption: "behind the espresso machine", span: "feature" },
  { image: "/media/archive/a-wave-from-the-counter.jpg", imageAlt: "A smiling barista waves from behind the counter, with stacked mugs in the foreground.", caption: "a wave from the counter" },
  { image: "/media/archive/pouring-behind-the-counter.jpg", imageAlt: "A barista pours a drink behind the counter beneath the 5AM Club wall lettering.", caption: "pouring behind the counter" },
  { image: "/media/archive/laughing-in-the-green-chair.jpg", imageAlt: "A man laughs while seated in a green armchair beside a large red-leafed plant.", caption: "laughing in the green chair" },
  ] },
];

/** Silent autoplay loops. Encoded with no audio track at all. */
export const clips: Clip[] = [
  { src: "/media/clips/carnival-crowd-streamers-up.mp4", poster: "/media/clips/carnival-crowd-streamers-up.poster.jpg", label: "Three women in carnival costumes on a crowded street with gold streamers overhead", caption: "carnival crowd, streamers up" },
  { src: "/media/clips/matcha-coconut-water-pour.mp4", poster: "/media/clips/matcha-coconut-water-pour.poster.jpg", label: "matcha, coconut water pour", caption: "matcha, coconut water pour" },
  { src: "/media/clips/oat-milk-pour-cookie.mp4", poster: "/media/clips/oat-milk-pour-cookie.poster.jpg", label: "oat milk pour, cookie", caption: "oat milk pour, cookie" },
  { src: "/media/clips/strawberry-syrup-pour.mp4", poster: "/media/clips/strawberry-syrup-pour.poster.jpg", label: "Strawberry syrup and passionfruit poured over ice into a cup on a scale", caption: "strawberry syrup pour" },
  { src: "/media/clips/matcha-poured-affogato-style.mp4", poster: "/media/clips/matcha-poured-affogato-style.poster.jpg", label: "matcha poured, affogato style", caption: "matcha poured, affogato style" },
  { src: "/media/clips/surprise-two-iced-coffees.mp4", poster: "/media/clips/surprise-two-iced-coffees.poster.jpg", label: "man peeks over two empty mason mugs, then they're filled with iced coffee", caption: "surprise, two iced coffees" },
  { src: "/media/clips/caramel-drizzle-iced-coffee.mp4", poster: "/media/clips/caramel-drizzle-iced-coffee.poster.jpg", label: "whipped cream and caramel drizzled over an iced coffee in a 5AM Club glass", caption: "caramel drizzle, iced coffee" },
  { src: "/media/clips/strawberry-drink-splash.mp4", poster: "/media/clips/strawberry-drink-splash.poster.jpg", label: "strawberry drink splashing out of a cup on a wooden table", caption: "strawberry drink, splash" },
  { src: "/media/clips/matcha-pour-filling-up.mp4", poster: "/media/clips/matcha-pour-filling-up.poster.jpg", label: "matcha pouring into an empty branded glass on a wooden table", caption: "matcha pour, filling up" },
  { src: "/media/clips/whisking-matcha-to-green.mp4", poster: "/media/clips/whisking-matcha-to-green.poster.jpg", label: "close-up of matcha powder being whisked into liquid in a ceramic bowl", caption: "whisking matcha to green" },
  { src: "/media/clips/slider-sandwich-revealed.mp4", poster: "/media/clips/slider-sandwich-revealed.poster.jpg", label: "hands presenting a beef or lamb slider on a plate at an empty table", caption: "slider sandwich, revealed" },
  { src: "/media/clips/milk-pour-sidewalk-table.mp4", poster: "/media/clips/milk-pour-sidewalk-table.poster.jpg", label: "steel pitcher pours milk into an iced coffee on a glass cafe table with a street scene blurred behind", caption: "milk pour, sidewalk table" },
  { src: "/media/clips/lavender-oat-matcha-layered.mp4", poster: "/media/clips/lavender-oat-matcha-layered.poster.jpg", label: "hand stirs a green matcha drink, adds ice, then pours in oat milk to build a layered lavender oat matcha", caption: "lavender oat matcha, layered" },
  { src: "/media/clips/espresso-pull-colored-light.mp4", poster: "/media/clips/espresso-pull-colored-light.poster.jpg", label: "close shot of an espresso machine portafilter under shifting blue and red accent light as a shot pulls", caption: "espresso pull, colored light" },
];
